- id: docformatter-conda
  name: docformatter-conda
  entry: docformatter -i --config pyproject.toml
  language: conda
  description: "Formats docstrings to follow PEP 257."
  types: [python]
  additional_dependencies: []
